### ISSUE TITLE
您好，感谢您的工作。我已经编译可以运行了，但是为什么没有可视化图像显示呢，请教一下

### ISSUE THREAD

**Issue by maxee1900** [xukuanHIT/AirVO#42]

**Comment by xukuanHIT** [comment]
@maxee1900  Hi, you can subscribe to the output topics and view them in rviz. The topic names can be set in config files.

**Comment by maxee1900** [comment]
thank you! another question: why frame process time is 400~500ms in my pc.  my computer gpu is NVIDIA® GeForce® MX250

**Comment by xukuanHIT** [comment]
@maxee1900 Hi, for each stereo image pair, AirVO will perform SuperPoint, SuperGlue and line detection twice in a single thread, so it can only run in real-time on good GPU, such as NVIDIA Geforce RTX 3090. You can read the paper for more details. This problem will be addressed in our following work.

**Comment by maxee1900** [comment]
Thank you very much!
