### ISSUE TITLE
Low performance platform testing

### ISSUE THREAD

**Issue by LanZY2021** [xukuanHIT/AirVO#46]
Hello, thank you so much for open-source the code.
I have read your paper. The experimental platform is RTX3090, and the feature extraction time is only 15ms. Have you tried the computing platform with low performance, such as RTX3060 of notebook, and how long is the time?
I failed to run through your code, so I ask you this question. I really hope to get your answer.

**Comment by xukuanHIT** [comment]
@LanZY2021 Hi, I don't have an RTX3060. But someone has tried to run AirVO on MX250. You can refer to #42
