### ISSUE TITLE
sorry， fatal error: NvInferRuntime.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by BoyLazyA** [xukuanHIT/AirVO#47]
[  2%] Building CXX object Thirdparty/TensorRTBuffer/CMakeFiles/TensorRTBuffer.dir/src/logger.cpp.o

In file included from /home/kkk/workspace/llll/Thirdparty/TensorRTBuffer/include/logger.h:20,

                 from /home/kkk/workspace/llll/Thirdparty/TensorRTBuffer/src/logger.cpp:17:

/home/kkk/workspace/llll/Thirdparty/TensorRTBuffer/include/logging.h:20:10: fatal error: NvInferRuntime.h: 没有那个文件或目录

   20 | #include <NvInferRuntime.h>

      |          ^~~~~~~~~~~~~~~~~~

compilation terminated.

make[2]: *** [Thirdparty/TensorRTBuffer/CMakeFiles/TensorRTBuffer.dir/build.make:76：Thirdparty/TensorRTBuffer/CMakeFiles/TensorRTBuffer.dir/src/logger.cpp.o] 错误 1

make[1]: *** [CMakeFiles/Makefile2:162：Thirdparty/TensorRTBuffer/CMakeFiles/TensorRTBuffer.dir/all] 错误 2

make: *** [Makefile:91：all] 错误 2

**Comment by zhangxiao19980516** [comment]
请问你是怎么解决的？
