### ISSUE TITLE
CMake Error: g2o 

### ISSUE THREAD

**Issue by ZJJ2022415** [xukuanHIT/AirVO#50]
Excuse me, I encountered a g2o problem when compiling. How can I solve it?

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
G2O_INCREMENTAL_LIBRARY
    linked by target "air_vo_lib" in directory /home/zjj/AirVO_ws/src/AirVO-master
G2O_INTERACTIVE_LIBRARY
    linked by target "air_vo_lib" in directory /home/zjj/AirVO_ws/src/AirVO-master
G2O_SOLVER_CHOLMOD
    linked by target "air_vo_lib" in directory /home/zjj/AirVO_ws/src/AirVO-master
G2O_SOLVER_CSPARSE
    linked by target "air_vo_lib" in directory /home/zjj/AirVO_ws/src/AirVO-master
G2O_SOLVER_CSPARSE_EXTENSION
    linked by target "air_vo_lib" in directory /home/zjj/AirVO_ws/src/AirVO-master
G2O_VIEWER_LIBRARY
    linked by target "air_vo_lib" in directory /home/zjj/AirVO_ws/src/AirVO-master

-- Configuring incomplete, errors occurred!
See also "/home/zjj/AirVO_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/zjj/AirVO_ws/build/CMakeFiles/CMakeError.log".

Thanks！

**Comment by ZJJ2022415** [comment]
Which version of g2o are you using?

**Comment by xukuanHIT** [comment]
@ZJJ2022415 Hi, we use the latest version. Please tell me the installation location of your g2o library.

**Comment by xukuanHIT** [comment]
@ZJJ2022415 Hi, we use the latest version. Please install these [optional requirements](https://github.com/RainerKuemmerle/g2o/blob/master/README.md#optional-requirements) before installing g2o.

**Comment by ZJJ2022415** [comment]
I have solved the problem, thank you.
