### ISSUE TITLE
about runing enviroment

### ISSUE THREAD

**Issue by ynma-hanvo** [xukuanHIT/AirVO#53]
thanks for your great efforts.  will it run on  environment of   cuda 10.2   with tensorrt, and ROS melodic?

**Comment by xukuanHIT** [comment]
@ynma-hanvo Hi, thanks for your interest. We have not tested on the environments you mentioned. ROS melodic should be no problem because we don't use too many functions of ROS. But I'm not sure whether a lower cuda version is okay. As for the TensorRT, it's better to use v8.4.1.5.

**Comment by ynma-hanvo** [comment]
> @ynma-hanvo Hi, thanks for your interest. We have not tested on the environments you mentioned. ROS melodic should be no problem because we don't use too many functions of ROS. But I'm not sure whether a lower cuda version is okay. As for the TensorRT, it's better to use v8.4.1.5.

thanks for your reply.  I will upgrade my workstation to cuda11.6 and test.
