### ISSUE TITLE
superglue and superpoint failed

### ISSUE THREAD

**Issue by ynma-hanvo** [xukuanHIT/AirVO#54]
hi, i did install cuda-11.6.2 and tensorrt 8.4  and successfully compiled the code. 
but it stucked in the  network  building  step;    the superglue engine building hanging there; 

i wish to create the onnx file by myself using the convert2onnx folder;   do you have a environment.yml file for creating the conda env.
thanks a lot;

**Comment by xukuanHIT** [comment]
@ynma-hanvo Hi, generating .engine files for the first time will take some time, please wait patiently.

**Comment by ynma-hanvo** [comment]
ooh, yes. you are right;   my gpu is gt1660 Ti , which takes almost 20 minutes; 
 excellent work!
