### ISSUE TITLE
Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 18969068147** [xukuanHIT/AirVO#55]
After I runned the command "roslaunch air_vo oivio.launch", the following error I got:
config_file = /home/ru/catkin_ws/src/AirVO/configs/configs_oivio.yaml
path = /home/ru/oivio/MN_015_GV_01/husky0/cam0/data
**Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory** //the libcublasLt.so lib is exist,but the libcublasLt.so.12 is not exist. I don't konw why???
[air_vo-2] process has died [pid 517129, exit code -6, cmd /home/ru/catkin_ws/devel/lib/air_vo/air_vo __name:=air_vo __log:=/home/ru/.ros/log/71b0e9b6-b836-11ed-b3a2-cb4f55628a0f/air_vo-2.log].
log file: /home/ru/.ros/log/71b0e9b6-b836-11ed-b3a2-cb4f55628a0f/air_vo-2*.log
Another problem is that I wonder to known the  meaning of "exit code -6" ?

**Comment by xukuanHIT** [comment]
@18969068147 Hi, we have not met this problem. You can try to use the provided docker environment to solve this kind of problem.
