### ISSUE TITLE
docker: Error response from daemon: failed to create shim task

### ISSUE THREAD

**Issue by ZhiYiXinNan** [xukuanHIT/AirVO#57]
![image](https://user-images.githubusercontent.com/126838395/222742543-2ec87bba-5514-4397-ab93-cb7273785bba.png)
How can I debug these issues?

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan Hi, do you have installed the Nvidia driver and Nvidia docker?

**Comment by ZhiYiXinNan** [comment]
I have installed the docker

**Comment by ZhiYiXinNan** [comment]
![image](https://user-images.githubusercontent.com/126838395/222756185-e034d360-1be3-4755-9a25-86b264140361.png)
I have installed nvidia driver ,but SMI can't communicate with the driver

**Comment by ZhiYiXinNan** [comment]
my use is vmware workstation

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan Hi, docker and Nvidia-docker (https://github.com/NVIDIA/nvidia-docker) are different. I have not used VMware. It seems that the Nvidia driver is not available in your environment.

**Comment by ZhiYiXinNan** [comment]
I am preparing change my enviroment,so,if I choose to use the docker you provite,should I need to install the dependencies like ROS ,OPenCV4.2.0,CUDA...?Or I should install these dependencies first then install docker and Nvidia-docker

**Comment by ZhiYiXinNan** [comment]
I am preparing change my enviroment,so,if I choose to use the docker enviroment you provide,should I need to install the dependencies like ROS ,OPenCV4.2.0,CUDA 11.6...?Or I just need to run the two docker commands like this.
![image](https://user-images.githubusercontent.com/126838395/222939291-52c4a901-8544-453b-86a0-cfa7b7d90897.png)

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan Hi, these dependencies have been integrated into the docker environment.

**Comment by ZhiYiXinNan** [comment]
Appreciate!One more quesetion,if I want to change the code to do my research and test,will the docker enviroment also need to be changed? Or I just need to change the codes ,and run the two commands,then the codes I changed will run as I wish
![](https://user-images.githubusercontent.com/126838395/222939291-52c4a901-8544-453b-86a0-cfa7b7d90897.png)

**Comment by ZhiYiXinNan** [comment]
Appreciate!One more quesetion,if I want to change the code to do my research and test,will the docker enviroment also need to be changed? Or I just need to change the codes ,and run the two commands,then the codes I changed will run as I wish

**Comment by ZhiYiXinNan** [comment]
Does the docker environment include the data.like ovio euroc .etc....?

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan Hi, code and data are not in the docker.

**Comment by ZhiYiXinNan** [comment]
hello,where should I put the data in? I have install the docker environment ,but i don't know what path  should I put the data in.

**Comment by ZhiYiXinNan** [comment]
I try to put the euroc dataest under /home/zzj like this
![2023-03-08 19-57-42 的屏幕截图](https://user-images.githubusercontent.com/126838395/223707505-579775b5-a8cc-46b9-a4c0-2eda8fff2a5f.png)

**Comment by ZhiYiXinNan** [comment]
![2023-03-08 22-26-59 的屏幕截图](https://user-images.githubusercontent.com/126838395/223739052-bf9eff50-c591-48ed-87cb-8dd7f925860b.png)
Do I need to  put the data into the docker environment?

**Comment by ZhiYiXinNan** [comment]
Do I need to put the data into the docker environment?
![2023-03-08 22-34-19 的屏幕截图](https://user-images.githubusercontent.com/126838395/223741050-b16fadf6-ceb7-4d34-8585-a42ea5179792.png)

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan Hi, I think these two links may be helpful for you.
https://docs.docker.com/storage/

**Comment by ZhiYiXinNan** [comment]
you mean i should put the dataest V1_02_medium in /media/xukuan/somethings2/ubuntu_files/data/euroc?

**Comment by ZhiYiXinNan** [comment]
你好，我实在搞不明白这个dataroot为什么一直告诉我"doesn't exist "不存在，无论我是自己手动修改路径 还是尝试将数据集拷贝到容器里都失败了，请问有什么好的解决方法吗？

**Comment by ZhiYiXinNan** [comment]
![2023-03-09 14-47-00 的屏幕截图](https://user-images.githubusercontent.com/126838395/223942749-0b4ef7d7-46eb-46cb-a828-5149293bb245.png)
It stuck,what can I do?

**Comment by ZhiYiXinNan** [comment]
![2023-03-09 15-46-44 的屏幕截图](https://user-images.githubusercontent.com/126838395/223954874-1da6105f-4989-4ecb-926a-d912f605dfa9.png)
when I run "roslaunch air_vo euroc.launch",it stuck for long time ,after waiting it shows that
![2023-03-09 15-48-30 的屏幕截图](https://user-images.githubusercontent.com/126838395/223955354-8c6f7500-d0d5-42c9-bef2-29cbe8caa51e.png)

**Comment by ZhiYiXinNan** [comment]
and shows Failed when extracting point features
![2023-03-09 15-49-53 的屏幕截图](https://user-images.githubusercontent.com/126838395/223955775-a5ef09eb-6b87-4537-8a59-ea9e25efe985.png)

**Comment by ZhiYiXinNan** [comment]
My GPU is GeForce RTX3070

**Comment by ZhiYiXinNan** [comment]
Hello, I have deal the dataroot problem ,but when I run "roslaunch air_vo euroc.launch",it stuck for long time ,after waiting it shows that
![2023-03-09 16-39-47 的屏幕截图](https://user-images.githubusercontent.com/126838395/223966926-b282e3a2-d361-48b1-bdab-e11bbf063e4d.png)
and stuck for long time and told me failed when extracting point features

![2023-03-09 16-42-20 的屏幕截图](https://user-images.githubusercontent.com/126838395/223967511-227d9599-3c9c-409a-a5cd-059e52e9c142.png)
I am anticipating your help and will be appreciate for it

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan Hi, the first picture shows the code has run successfully and the trajectory has been saved.
For the problem in the second picture, please take a look at [this link](https://github.com/xukuanHIT/AirVO/issues/43#issuecomment-1382732091) to show more debug information.
For the long time stuck, please refer to #54 .

**Comment by ZhiYiXinNan** [comment]
what about  the problem in first picture?
![image](https://user-images.githubusercontent.com/126838395/224064455-221c76d2-a7d8-4a30-a305-83f872e15589.png)

**Comment by ZhiYiXinNan** [comment]
Yes ,you are right ,the first time I run the code is too slow ,then will be faster,but I still can not deal with the error,could you please tell me what wrong with it,Is my environment not true?

**Comment by ZhiYiXinNan** [comment]
I glanced over the link you gave to me ,I found I don't generate "(find air_vo)/debug" in AirVO,what cause it?
![2023-03-10 09-48-06 的屏幕截图](https://user-images.githubusercontent.com/126838395/224202372-cb3f0aa6-cc7f-4ee4-9e1e-705ebdd8c4d5.png)

**Comment by ZhiYiXinNan** [comment]
![2023-03-10 18-17-09 的屏幕截图](https://user-images.githubusercontent.com/126838395/224290282-9a91bf80-d4d1-4781-9f5c-eb05872fcc78.png)
how can I debug this problem?Appreciate for your  help

**Comment by ZhiYiXinNan** [comment]
Is this problem caused by the code?
![2023-03-10 18-17-09 的屏幕截图](https://user-images.githubusercontent.com/126838395/224317307-068eec11-9919-4e4e-80c5-aa8acb1bf73c.png)

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan It seems that the code has finished running and then exits. I think you can ignore it.

**Comment by ZhiYiXinNan** [comment]
But how can I See the results?



---Original---
From: "Xu ***@***.***&gt;
Date: Sat, Mar 11, 2023 13:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xukuanHIT/AirVO] docker: Error response from daemon: failed tocreate shim task (Issue #57)




 
@ZhiYiXinNan It seems that the code has finished running and then exits. I think you can ignore it.

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan 1. Configure related paths in launch files to save trajectory.
2. Configure related ros topic names in "config files" to visualize the results in rviz

**Comment by ZhiYiXinNan** [comment]
Hello,you mean I can ignore "process has died "?

**Comment by ZhiYiXinNan** [comment]
Hello, do you mean I can ignore the "process has died"on screen,and it will not influence rviz running,so I just need to run rviz then I can see the result ,all I can do is  check the configure related path?

**Comment by ZhiYiXinNan** [comment]
I  am appriciated  for your help ,but please allow me ask one more question,what software do you use to compare different SLAM scheme,and does the "process has died"on screen will influence my following research(compare different SLAM scheme)? Appriciate!

**Comment by ZhiYiXinNan** [comment]
I  am appriciated  for your help ,but please allow me ask one more question,what software do you use to compare different SLAM scheme,and does the "process has died"on screen will influence my following research(compare different SLAM scheme)? Appriciate!

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan 1. [evo](https://github.com/MichaelGrupp/evo)
2. No

**Comment by ZhiYiXinNan** [comment]
Thank you ,I will try as you said .

**Comment by ZhiYiXinNan** [comment]
> @ZhiYiXinNan It seems that the code has finished running and then exits. I think you can ignore it.
I think about your advice,how could you make sure the code has run successfully Under the premise of showing “process has died”on screen?

**Comment by ZhiYiXinNan** [comment]
How can I visualize the results in rviz? When I run "rosrun rviz rviz" It shows 
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

Do you know how to deal with the problem?Appreciated

**Comment by xukuanHIT** [comment]
@ZhiYiXinNan #44
