### ISSUE TITLE
Is it possible to run w/ a bag file?

### ISSUE THREAD

**Issue by jlee-67** [xukuanHIT/AirVO#58]
Hello,

Thank you for working on this research project. I got everything to work perfectly - one thing I was just wondering was if I could use this with my bag file (I have a bag file recorded using flir_boson sensor). 

Thank you.

**Comment by xukuanHIT** [comment]
@jlee-67 Hi, the input must be image sequences now. You can use [this script](https://entuedu-my.sharepoint.com/:u:/g/personal/kuan_xu_staff_main_ntu_edu_sg/EVqjOjV6RNFMsmM_6Vc6NoABytryLGVn8LqSjLbayqeiHQ?e=ruyJrU) to convert your bag to the image sequence, or you can also modify the code to receive ros topic as input.
